# -*- coding: utf-8 -*-
"""Alura_DataScience.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NkA7rd8GnoAFXvXQVpw7v1G8LW43a333
"""

# Instalar as bibliotecas necessárias
!pip install yagmail
!pip install keyring

# Importar as bibliotecas necessárias
import yagmail
import pandas as pd

# Configuração do e-mail
email_remetente = "esleyfacanali@gmail.com"  # Substitua pelo seu e-mail
senha_remetente = "prdshhlsrgqxqavk"  # Substitua pela sua senha ou App Password

# Caminho para o arquivo Excel
caminho_arquivo_excel = "clientes.xlsx"  # Substitua pelo caminho do seu arquivo Excel

# Ler o arquivo Excel
try:
    df = pd.read_excel(caminho_arquivo_excel)
except Exception as e:
    print(f"Erro ao ler o arquivo Excel: {e}")
    exit()

# Verificar se as colunas necessárias estão presentes no arquivo
if not {'Nome', 'email'}.issubset(df.columns):
    print("O arquivo Excel precisa ter as colunas 'Nome' e 'Email'.")
    exit()

# Enviar e-mails personalizados
try:
    # Criar o cliente yagmail com as credenciais
    yag = yagmail.SMTP(email_remetente, senha_remetente)

    # Iterar sobre as linhas do DataFrame
    for _, linha in df.iterrows():
        nome = linha['Nome']  # Nome do cliente
        email = linha['email']  # E-mail do cliente

        # Criar uma mensagem personalizada
        mensagem = f"Olá {nome},\n\nEspero que esta mensagem encontre você bem!\n\nAtenciosamente,\nSua Empresa"

        # Enviar o e-mail
        yag.send(
            to=email,
            subject="Mensagem Personalizada",
            contents=mensagem
        )
        print(f"E-mail enviado para {nome} ({email}).")
except Exception as e:
    print(f"Erro ao enviar e-mails: {e}")